FightPandemics/FightPandemics

client/package.json, client/src/App.js, client/src/auth_config.json, client/src/index.js, client/src/pages/About.js, client/src/pages/Header.js, client/src/pages/Medical.js, client/src/react-auth0-spa.js, client/src/utils/history.js
* Auth0
* About
* Fixed svg logo issue
* Medical Info (Initial Page)
=> Implementation of Features

README.md, backend/config/keys_dev.example.js
Please let me know if I'm missing anything!
=> Update README with steps to start developing

backend/config/keys_prod.js, client/src/pages/Medical.js, server.js
- The bug was caused by the incorrect use of axios, so I did a quick fix and I'll probably extract the api layer away from the component layer soon
- My vscode auto-formats code upon saving and is prettier-enabled so most of the changes come from the IDE reformatting the code 🤪 I can add the prettier config in the codebase!
- added `useUnifiedTopology` in the mongoose connection config because it keeps complaining, I referred from https://github.com/Automattic/mongoose/issues/8156
- I also referred to https://github.com/manualzuru/FightPandemics.com/pull/15 for the fix on getting the geolocation
=> Small fixes and refactor mainly on the Medical.js

client/src/components/Button/FilterOptionButton.js, client/src/components/FilterBox/FilterBox.js, client/src/constants/colors.js, client/src/pages/Feed.js, client/src/routes.js
There are a few things I need to work on still:
- Need to get the correct bold text 
- Need to bold the down arrow
- Need to fix the positioning of the down arrow a bit
But overall I think the implementation is close!
**Original:**
**This PR:**
=> Frontend Feed - Filter box

client/src/pages/ResultsPage.js, client/src/pages/SymptomsCheck.js, package-lock.json
- Add a results page to display the user answers.
- the recommendation bit is missing as per the mockup. This is from the user answers, need guidance on this.
- The Done button will redirect to the feed after the feed feature is completed.
Am currently fixing the styles on the Done button and digits.
=> Show answers selected by user on results page

client/src/index.scss, client/src/templates/layouts/NavigationLayout.js
A few style updates and added a close icon so the menu matches the design.
Also added a root font size for relative units.
=> Drawer menu style tweaks

client/src/components/Accordion/FilterAccordion.js, client/src/components/Button/FeedbackButton.js, client/src/components/Button/FilterOptionButton.js, client/src/components/Emoji/index.js, client/src/components/Feed/FilterAccordion.js, client/src/components/Feed/Post.js, client/src/components/Icon/SvgIcon.js, client/src/components/Input/LocationSearch.js, client/src/components/Input/PasswordInput.js, client/src/components/Input/TextInput.js, client/src/pages/About.js, client/src/pages/Home.js, client/src/pages/Login.js, client/src/pages/ResultsPage.js, client/src/templates/layouts/LogoLayout.js, client/src/templates/layouts/NavigationLayout.js
- Removed all the unused imports and variables because of the warnings thrown, pardon me if I'm a little too OCD about this 😢 
- Made small ui and styling changes on the About page in `About.js` so that its responsive
- Added `<Emoji />` component, because of the warnings thrown for using emojis in text too
- Added `cursor: pointer` to the social icons button on the login page. Since its a button, I guess pointer is good to represent that it's clickable
=> Removed unused imports & variables and Made small changes on About page

client/package-lock.json, client/package.json, client/src/assets/data/fakePosts.js, client/src/components/Accordion/FilterAccordion.js, client/src/components/Button/CustomButton.js, client/src/components/Button/FilterOptionButton.js, client/src/components/Feed/Comments.js, client/src/components/Feed/FilterBox.js, client/src/components/Feed/NestedComments.js, client/src/components/Feed/Post.js, client/src/components/Feed/PostCard.js, client/src/components/Feed/PostSocial.js, client/src/components/Feed/Posts.js, client/src/components/List/CustomList.js, client/src/components/Tag/FilterTag.js, client/src/components/Typography/Title/FilterTitle.js, client/src/index.js, client/src/styles/theme.scss
- Fixed sizing and positioning of elements across the Feed
- The Create Post icon floats while scrolling the feed
- Fixed font weight issues by adding more weights when importing Poppins
- Incorporated copy-to-clipboard functionality using a react library (onClick it will show a modal alerting "Link Copied!")
-  Installed `antd` in order to use the Comment component
- Added like/unlike functionality
- The count for share will increase only once onClick
- Clicking comments will show comments
- Rendered nested comments (still need to style them)
WIP:
- Styling comments
- Add functionality to reply to comment
- Once the backend for auth, posts, comments, and likes are done I'll work on API integration
=> Feed Frontend: style fixes and render nested comments

README.md
I noticed there were confusions about our tech stack so I decided to update the README. As we have new people join and help we can direct them to the README so they are familiarized. Feel free to make any edits!
=> Update README with tech stack

client/src/assets/data/fakePosts.js, client/src/components/Feed/NestedComments.js, client/src/components/Feed/Post.js, client/src/components/Feed/PostCard.js, client/src/components/Feed/StyledComment.js, client/src/components/Input/AutoSize.js, client/src/components/Input/TextArea.js, client/src/utils/userInfo.js
- Changed input elements to be textareas so that the height auto sizes when there's a long comment
- Styled comments and nested comments
- Added the small heart icon in the comments
WIP
- Implement API once backend is done
- Clean up dummy data
- Clean up code for better readability 
- Adding functionality to "View More" to truncate post description 
Textarea height resizing:
Commenting and nested commenting:
=> Feed Frontend: Nested commenting

client/src/components/StepWizard/AnswerButton.js, client/src/pages/NeedHelp.js
* Integrated the new styled components I created for the step wizard to make the wizards more consistently styled with each other. There are still issues with the wizards, largely in terms of flow, but this deals with the styling in the NeedHelp wizard.
* fixed bug with the onChange function on the email input using the wrong value. evt is all we need on these antd-mobile inputs
This relates to #122 
I cherry picked my commits into a fresh branch from master at 5384690
=> Add styled components needhelp

client/src/pages/Medical.js, client/src/setupProxy.js, docker-compose.yml
I also partially fixed the callout to the geo endpoint, but we still need to authenticate to actually get a response back.
=> Fix client backend proxy

client/src/components/Header.js, client/src/components/StepWizard/AnswerButton.js, client/src/pages/Login.js, client/src/pages/NeedHelp.js, client/src/pages/OfferHelp.js, client/src/routes.js
Removed unused variables noted by the console warnings.
**Before:** 
**After:**
=> Remove unused variables 

client/package-lock.json, client/package.json, client/src/index.js
remove react-alert 3rd party library from npm
=> remove react-alert 3rd party lib

client/src/assets/icons/back-arrow.svg, client/src/assets/icons/next-arrow.svg, client/src/components/Button/FeedbackButton.js, client/src/components/Button/ImageButton.js, client/src/components/Icon/back-arrow.js, client/src/components/Icon/next-arrow.js, client/src/components/StepWizard/AnswerButton.js, client/src/components/StepWizard/StepTitle.js, client/src/components/StepWizard/WizardCheckboxItem.js, client/src/components/StepWizard/WizardNav.js, client/src/components/StepWizard/WizardProgress.js, client/src/components/StepWizard/index.js, client/src/pages/Home.js, client/src/pages/NeedHelp.js, client/src/pages/OfferHelp.js
- Updated text based on the most recent mobile design on Figma
- Fixed some styling related to positioning, typography, checkboxes, arrow icons, etc.
=> Update text and styling in Landing + OfferHelp + NeedHelp related pages

backend/lib/components/Auth0.js, backend/lib/endpoints/auth.js, backend/lib/endpoints/schema/auth.js, client/src/actions/authActions.js, client/src/pages/Login.js, client/src/utils/hooks.js
Updated signup & login with OAuth / social media providers
Currently, when calling `/api/oauth`  with the code to get an access token, we also get user info from Auth0 and send email / email verified to frontend that can use this to complete the profile (could also add image)
=> Social media auth

client/src/pages/CreatePost.js
- User must add at least one tag (required field), otherwise an error message appears
- Add spacing between title and description
- Rename fields to match Post schema
- Begin setup for API integration
=> Post Creation Frontend: update required fields, begin setup for API integration

.github/workflows/staging-workflow.yml
This fixes the staging workflow for continuous deployment to AWS.
* Set `TF_VAR_env_name` to staging
=> Fix staging workflow

README.md
What does it aim to achieve, and why?
* A few notes on your commits.
* To help understand them.
=> Adds build status badge

backend/package.json, docker-compose.yml
Closes #215 
Allow developers to attach a debugger to a running process in dev. mode
* Adds `--inspect` flag to `nodemon` process to allow to attach a debugger
=> Allows to connect debugger to an application in the dev mode

backend/lib/endpoints/schema/auth.js, backend/lib/endpoints/schema/geo.js, backend/lib/endpoints/schema/organizations.js, backend/lib/endpoints/schema/posts.js, backend/lib/endpoints/schema/users.js, backend/lib/endpoints/schema/utils.js
Closes #119 
Provide a simple way to define schemas that do not allow unexpected properties.
Defines function `strictSchema`
Uses the `strictSchema` in all existing schemas
=> Adds a helper function to define schema with no additional parameters

client/src/App.js, client/src/GlobalStyles.js, client/src/actions/authActions.js, client/src/index.js, client/src/pages/EditProfile.js, client/src/pages/Home.js, client/src/pages/Login.js, client/src/pages/Medical.js, client/src/pages/Profile.js, client/src/templates/layouts/NavigationLayout.js
=> Clear console warnings and print statements

client/src/reducers/index.js, client/src/reducers/sessionReducer.js, client/src/reducers/userReducer.js
Following with the User Profile PR, this PR creates a `userReducer` and a `user` slice of state to align with a [normalized Redux state shape](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape/)
=> Create a user slice of state in Redux state

backend/config.js, backend/package.json, backend/server.js, package-lock.json
Closes #211 
Implements config validation using `env-schema`
* Adds `env-schema` dependency
* Adds schema for env. variables used to create a config object
=> Uses "env-schema" to validate application config

backend/lib/endpoints/organizations.js
Unauthenticated users should be able to see organizations, this pull request attempts to achieve that.
I removed the `preValidation` hooks from lines 38 and 54, eslint did the rest of the changes 😅
=> Allow unauthenticated users to fetch organizations

backend/lib/endpoints/posts.js
- Remove preValidation in api/posts/:postId
=> Allow unauthenticated users to access a post

docker-compose.yml
Since we are using `mongoose.createConnection()` in the code which requires a database name to be specified, we should initialize a database in the Mongo container, and also update `MONGO_URI` to include the database name.
Closes #236 
* Set `MONGO_INITDB_DATABASE` in the `mongo` container to initialize a database called `fightpandemics`
* Update `MONGO_URI` environment variable in the `backend-service` container to include the database name.
=> Init Mongo with fightpandemics DB

backend/lib/endpoints/auth.js, backend/lib/endpoints/schema/auth.js
Closes #220 
Aditional check to ensure that a user has entered password correctly 
* Adds `confirmPassword` field
* Checks that a password was entered correctly twice
=> Adds "confirmPassword" field to the "signup" request body

client/src/pages/Login.js
Blocked by #242 
Closes #220 
Adds confirm password field to the signup page
* Updates to work with #242
=> Adds "confirmPassword" field to the signup form

client/src/components/Feed/ButtonModal.js, client/src/components/Feed/FilterAccordion.js, client/src/components/Feed/FilterBox.js, client/src/components/Feed/Post.js, client/src/components/Tag/AddTags.js, client/src/components/Tag/FilterTag.js, client/src/pages/Feed.js
- Updated styles in Feed and CreatePost to match Figma
- Refactored `FilterTag` to return a styled-component
=> Update Feed and CreatePost styles

client/src/pages/Login.js
The "confirmPassword" field was removed and it broke the sign up form.
* Restores the "confirmPassword" field
=> Restores "confirmPassword" field on the SignUp form

main.tf
Now that we have `NODE_ENV` as a required environment variable, we need to add it to Terraform so that it can be set in staging.
* Add `NODE_ENV` environment variable to Terraform `main.tf` file
=> Set NODE_ENV in Terraform

client/src/components/CookieAlert.js
=> solve the icon issue in CookieAlert

client/src/components/CookieAlert.js
solve cookie alert appear once
=> solve cookie alert appear once

backend/lib/endpoints/users.js
https://github.com/FightPandemics/FightPandemics/issues/287
=> fix user last name update

client/src/pages/NeedHelp.js
What does it aim to achieve, and why?
Once submit button is clicked, it will redirected to feed page
* A few notes on your commits.
* To help understand them.
wrapped SubmitButton with <Link> to redirect to feed page.
=> submit button will redirected to feed page

client/src/components/Feed/FilterBox.js, client/src/components/Typography/Heading.js, client/src/components/Typography/TextLabel.js, client/src/pages/Profile.js
Sorry for the multiple pull requests, there was a merge issue!
=> #341 - Change Heading's static values to variables from theme.js

client/src/pages/OfferHelp.js, client/src/pages/SymptomsCheck.js
Added missing currentStep -1 and totalSteps -1 in the SymptomsCheck.js file.  Both were missing in two different location of the file.
=> fixed incorrect numbering on symptom checker

README.md
A rough guideline for handling time sensitive issues.
=> add guideline for time sensitive issues

client/src/components/Button/BaseButton.js, client/src/components/Button/LeftRightIconButton.js, client/src/components/Button/SubmitButton.js
Created a new button component the relies on submit button to meet the requirements of https://github.com/FightPandemics/FightPandemics/issues/294. This could refactored to rely on base button if preffered. It believe it meets the requirements of the issue.
I made some assumptions in regards to the function and design of the buttons:
- It only accepts a single icon and in some cases I think the background color will make the icon disappear on hover. I noticed this is the case for other buttons on the site, so assuming its ok here too.
- I have hard coded the width to be 192px, should this be more fluid?
- There were some other buttons which appear to deal with icons in the repo, I assumed that …
=> Added new LeftRightIconButton component

client/src/components/Feed/Post.js, client/src/components/TextAvatar/index.js, client/src/hooks/actions/feedActions.js, client/src/hooks/reducers/feedReducers.js, client/src/pages/Feed.js
https://github.com/FightPandemics/FightPandemics/issues/179
Add API post calls to Feed page.
Modified posts reducer and added endpoint call.
Note: These changes will not work if https://github.com/FightPandemics/FightPandemics/pull/373 is not merged before.
=> [179] Add api calls to feed page.

backend/lib/endpoints/posts.js
Changed author name composition with first and last to single name attribute to reflect user model changes
Change author name composition with first and last to single name attribute to reflect user model changes
* Change author name composition
* Fix edge case at `GET /posts/:postId`
=> Adjust post endpoints to reflect changes at user model

.github/pull_request_template.md
Documented PR criteria for the Github pull request template.
=> Update Github pull request template

client/src/pages/SymptomsCheck.js
fixed the numbering issue. Now it will be counting 8/8.
=> Fixed the numbering order for issue 356

client/src/pages/Home.js
Fix disappearing of description when screen rotate (mobile) issue https://github.com/FightPandemics/FightPandemics/issues/343
* Changed media query and also margin to match mockup design
=> fixed disappearing of description when rotate

backend/lib/models/Location.js
Add `state` and `zip` fields at the `Location` model
Closes #392
=> Add state and zip to location model

client/src/constants/theme.js, client/src/pages/Home.js
closes #430 
* fixed border-radius
* added background gradient to theme.js
* used background gradient for landing page to match Figma
=> fixed border-radius and background-gradient

backend/lib/endpoints/posts.js
Allow unauthenticated users to access the `/posts` endpoint to access the feed
- removed auth pre hook
- added logic for unauthenticated users, removing visibility filters and changing sorting from location to most recent
* A few notes on your commits.
* To help understand them.
=> Add options for unauthenticated user at /posts

client/src/components/Tag/AddTags.js, client/src/pages/CreatePost.js
Update AddTags Component to use ButtonTag.
1. [x] I have checked that no one else is working on similar changes.
2. [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
3. -not used- The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
4. [x] This branch is rebased/merged with the **latest master**.
5. [x] There are no merge conflicts.
6. [x] There are no console warnings and errors.
7. -not used- On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
=> Update AddTags Component to use ButtonTag.

client/src/components/Button/FeedbackButton.js, client/src/pages/Home.js
Changed homepage's background color from white to offWhite. Added white background to the ImageButtons.
#431
=> Added background color in home page

client/src/pages/Login.js
=> feat: hide twitter auth button for MVP #412

.github/workflows/review-workflow.yml, .github/workflows/staging-workflow.yml, backend/config.js, backend/lib/index.js, backend/lib/plugins/error-handler.js, backend/package-lock.json, backend/package.json, main.tf
Adding Sentry error notifier so that we can get alerted of Sentry errors in staging/production.
Summary of changes:
- Added Sentry npm package
- Added Fastify error handler plugin
- Updated Terraform/Github workflows to pass in environment variables needed for Sentry
Close #387.
=> Add Sentry error notifier

client/src/components/Footnote.js
closes #477 
Footer Links now redirect to the correct pages.
=> fixed footer links

client/src/assets/data/filterOptions.js, client/src/components/Feed/FiltersSidebar.js, client/src/pages/Feed.js
Corrected filter section spelling mistakes:
1.  From "create post" to "create a post"
2. From "From Whom" to "From whom"
3. From "View Results" to "View result"
4. From "Others" to "Other"
5. From "Something went wrong ..." to "Something went wrong..." (deleted the space between last letter and first dot)
6. …
=> fixed spelling mistakes on feed page and filter side page.

client/src/assets/data/filterOptions.js
Changed the text under filter section from "From Whom to Providers"
#
=> changed the text from whom to providers

backend/lib/endpoints/users.js
Missed this. It `User.findById(req.userId)`always evaluates to truth-y if not awaited so it always fails.
=> add await to User.findByid

README.md
Resolves #440 
@galeza let me know if this is sufficient to clarify the issue you encountered. https://github.com/FightPandemics/FightPandemics/pull/424#issuecomment-632588182
7. On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" …
=> doc that feature/ branches should be in the main repo

client/src/components/CreatePost/CreatePost.js, client/src/components/CreatePost/Form/Form.js, client/src/components/CreatePost/StyledPostAs.js
Creates confirmation modal after Creating Post
Steps:
go to feed page
click create post
select individual or organization
select a organization
click Share button
should appear confirmation modal
Closes #510
=> Create confirmation modal to post

client/src/components/CreatePost/Form/AskHelp.js, client/src/components/CreatePost/Form/OfferHelp.js
https://github.com/FightPandemics/FightPandemics/issues/530
Rename the share button to "Post"
=> Change submit button text from "Share" to "Post"

client/src/components/CreatePost/StyledCreatePost.js, package-lock.json
=> text color changed to darkerGray

main.tf
Set the `AUTH_APP_URL` environment variable based on the environment.
Note that this is a WIP. I need to do additional configuration setup in the Auth0 web console.
Please do not merge.
=> [WIP] Auth0 - Set AUTH_APP_URL based on environment

backend/lib/plugins/mongoose-connector.js
=> fix: update syncIndexes to fix bug with updated mongoose schema's

client/src/components/Feed/Comments.js, client/src/components/Feed/NestedComments.js, client/src/components/Feed/Post.js, client/src/hooks/actions/feedActions.js, client/src/hooks/reducers/feedReducers.js, client/src/pages/Feed.js
https://github.com/FightPandemics/FightPandemics/issues/181 Create comments in a post.
1. [x] I have checked that no one else is working on similar changes.
2. [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
3. [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
4. [x] This branch is rebased/merged with the **latest master**.
5. [x] There are no merge conflicts.
6. [x] There are no console warnings and errors.
7. [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
=> [181] Create comment in a post.

client/src/pages/PrivacyPolicy.js
Updated our Privacy Policy with the new content of 10.a .
closes #553
=> privacy policy 10.a updated

client/src/assets/data/createPostSettings.js
Changes the default visibility of a post from 'Forever' to 'Month'
Closes #543
=> [543] Small fix: Changes the default visibility of a post from 'Forever' to 'Month'

client/package-lock.json, client/src/components/StepWizard/StyledWizard.js, client/src/components/StepWizard/WizardContainer.js
=> fixed bug by adding overflow-x and y to  hidden

client/src/components/Header.js
https://github.com/FightPandemics/FightPandemics/issues/576
=> remove covid-19 info

client/src/templates/layouts/NavigationLayout.js
https://github.com/FightPandemics/FightPandemics/issues/577
=> remove data privacy

client/src/components/CreatePost/CreatePost.js
https://github.com/FightPandemics/FightPandemics/issues/520
=> hide scroll bar

main.tf
Fix AUTH_APP_URL to be the same for all review builds; this is necessary for Auth0 namespacing custom claims
=> Fix AUTH_APP_URL

client/src/components/CreatePost/CreatePost.js
=> fix: move overflow attribute to styles

client/src/components/Input/BaseInput.js, client/src/config.js, client/src/pages/CreateUserProfile.js, client/src/pages/Login.js, client/src/utils/validators.js
Closes #369 
add client-side validation for login/signup and create user profile pages
integrated with the react-hook-form errors, currently hard coded validation messages, they can be replaced by translation strings later
=> Client-side validation for login/signup and create user profile

client/src/components/Header.js, client/src/pages/CreateUserProfile.js, client/src/templates/RouteWithSubRoutes.js
fix authenticated check in nav menu's
=> fix login stuff / isAuthenticated prop in nav menu's

backend/config.js, backend/lib/index.js, backend/lib/logger.js, backend/package-lock.json, backend/package.json, main.tf
This PR adds logging to Papertrail, and also allows for the log level to be configurable using the `LOGGER_LEVEL` environment variable. By default, it will be set to `info`.
Resolves #571
=> Add Papertrail, and allow log level to be configurable

client/src/pages/OfferHelp.js
https://github.com/FightPandemics/FightPandemics/issues/594
=> fix feed link

client/src/components/CookieAlert.js, client/src/components/Icon/SvgIcon.js
Centers the text on the cookie banner refers
Refers to this issue #583 
=> aligning the text on the cookie batter to be centered

client/src/assets/data/createPostSettings.js
Changes the defaults when creating a new post to Worldwide and Forever
#523 
Before defaults: 
After defaults:
This change would set defaults to Worldwide | Forever to both Individual Posts & Org Posts
7. On the right …
=> changed default post settings when creating a new post

client/src/assets/icons/search-blue.svg, client/src/components/Input/InputError.js, client/src/components/StepWizard/StyledTextInput.js, client/src/components/StepWizard/WizardNav.js, client/src/pages/CreateUserProfile.js, client/src/pages/Login.js, client/src/pages/NeedHelp.js
Email validation to needs help page. Still unfinished. 
=> Added email-validation to needs help page.

README.md
updating readme to provide the right path for the documentation. 
N/A
=> updated README.md to provide the right path for the documentation

backend/lib/models/Post.js
https://github.com/FightPandemics/FightPandemics/issues/620
=> Add "Tech" to Post.types enum

client/src/components/Footnote.js
Added faq link on the foot note, working fine for both web and mobile views. This will resolve #541
=> FAQ added as per #541

client/src/components/Faq/FaqContainer.js, client/src/components/Faq/FaqLink.js, client/src/pages/Faq.js, client/src/routes.js
A starting point for creating a faq page. No design applied yet. Added some faqs already just to start, added a new page, with the faq path
#616
=> adding a new path for faq and added faqs

.github/workflows/production-workflow.yml, .github/workflows/review-workflow.yml, .github/workflows/staging-workflow.yml, main.tf
Setting up deployment to production through Github Actions.
I also fixed some other issues as well:
* Pass in the git commit properly - before it wasn't actually getting the commit from the environment variable properly, so I had to create a new step to output the commit hash, and then use that output to pass it to Terraform
* Pass in `aws_region` Terraform variable; this is necessary because the default region is `us-east-1`, but for production we are deploying to `eu-west-1`.
Closes #547
=> Add production deployment; fix staging/review workflows

client/src/components/Faq/FaqContainer.js, client/src/pages/Faq.js
This pull request adds more FAQs to the `/faq` page as well as changes the way the questions are being displayed. 
#616
=> added more FAQs and updated page looks

client/src/pages/Profile.js
This fixex the small bug that create an extra icon on the /profile page
#647
=> removing extra icon from the /profile route

client/src/pages/OfferHelp.js
Added email validation to offer help page using { validateEmail } from "utils/validators";
project progress under "Projects".
=> fixed email validation on offer help page

backend/lib/endpoints/posts.js
Resolves #653 
@robinv85  on your comment
> And makes me wonder why this got merged, should probably be caught by ESLint and preventing to commit...
husky will prevent this but **only** if installed and I think it can be skipped to. We could add to github actions workflows but right now that will create a lot more headaches than it is worth - we can look into this again post MVP. (Create a ticket?)
4. …
=> fix post patch undefined postProps

backend/scripts/import-posts/map-airtable-data.js
Airtable share_with (visibility in model) was changed to single-select.
Need to handle appropriately.
=> treat airtable post share_with as single-select

client/src/templates/layouts/MobileTabs.js
uncommented lines that are responsible of showing the red tagged emergency number since its not part of the MVP. 
- 1. I have checked that no one else is working on similar changes.
- 2. I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- 3. The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- 4. This branch is rebased/merged with the **latest master**.
- 5. There are no merge conflicts.
- 6. There are no console warnings and errors.
- 7. On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
=> Uncommented emergency num lines temp

client/src/components/Button/FeedbackButton.js, client/src/components/StepWizard/WizardSubmit.js, client/src/pages/OfferHelp.js
This issue came up again but with respect to size and alignment. This fix will take care of it. 
=> Fix button size to to be center on desktop and mobile

backend/lib/endpoints/posts.js, backend/lib/endpoints/schema/posts.js
Resolves #184 
So based on discussion and what I see in front end what I'm doing is putting objective ("offer", "request") as query param with the three filter sections into URI encoded JSON.
So for example:
`{{baseApiUrl}}/posts?skip=0&limit=100&objective=request&filter=%7B%22location%22:%7B%22coordinates%22:%5B-74,40%5D,%22country%22:%22US%22%7D,%22type%22:%5B%22Information%22,%22Medical%20Supplies%22%5D,%22fromWhom%22:%5B%22Community%22,%22University%22%5D%7D`
Which is decoded & parsed on server. 
This works and seems to work quite well but I'm not sure about fluent-schema validation - can you do something custom for this? Anyways we can come back to later. If we merge then me someone else. 
1. I have checked that …
=> Add filters to posts/ endpoint

client/package-lock.json
fix the package-lock file that wasn't updated after last auto upgrade from snyk
=> fix package-lock file

client/src/templates/layouts/MobileTabs.js
=> removing extra tabs from UI and only show feed

client/src/components/StepWizard/WizardNav.js
=> Fixing issue 695

client/package-lock.json, client/src/pages/NeedHelp.js
**It helps makes the bi-directional flow of the app consistent 
https://github.com/FightPandemics/FightPandemics/issues/599
7. On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" …
=> Fixed the bi-directional back-button- flow from feed to onbaording

client/src/components/Input/AddressInput.js, client/src/pages/CreateUserProfile.js, client/src/pages/EditAccount.js
This will get the location input working as before for Create User Profile. It also is working with Edit Account:
This is not ideal use of react & react-hook-form but we can refactor later and I we need these working so people can end-to-end test. 
But, there is another issue I realized about react-hook-form. The other places using location filter, the onboarding & feed filter - I don't they they are using react-hook-form anyways so we might need to wrap the address input (in a controller?) anyways so it can be used with/without react-hook-form.
@indirabhowmick if your husband has any suggestions based on his experience with react here is the item to look at.
1. I have …
=> get location input to work for create/edit profile

client/src/components/Faq/FaqContainer.js, client/src/pages/Faq.js
This PR is meant to fnialize the FAQ page at least for the soft launch and MVP-1. 
Resolves issue #616
=> finalized faq page update to close issue #616

backend/lib/endpoints/schema/auth.js
Added format email to backend/lib/endpoints/schema/auth.js'
=> Format email validation

client/src/templates/layouts/NavigationLayout.js
Fixing small missed link that was not merged on #589
=> Updated NavigationLayout.js since I misused link instead of Link

backend/lib/models/User.js, backend/package-lock.json, backend/package.json
Add a constraint to guarantee that the user's email is unique.
Closes #590
=> Add unique constraint to user's email at mongoose model

client/src/pages/NeedHelp.js
We want to keep consistency across our platform, so we need to have both Need Help and Offer Help Location input be equal.
This PR resolves #619
=> implemented LocationInput for Need Help location geo step

backend/lib/endpoints/schema/location.js, backend/lib/endpoints/schema/organizations.js, backend/lib/endpoints/schema/users.js
Resolves #748 
This relates to an issue I saw when reviewing #709 . Considering making PR into that branch but instead some items are not exactly related as I want to address all of proper location requirements.
Then we can merge master into #709
* address/coordinates should be required on location object
* location object should be required on create user
* location object should be required on create org BUT the current way it was defined was incorrect, it was making the last location property required (zip) not the object
3. The name of this branch is: …
=> Proper location requirements

.github/pull_request_template.md
suggestion to PR template
the ''🚨Before submitting this pull request🚨:'' and ''Please do NOT submit this PR if you have not done the following:'' copy are now only visible when submitting, so they appear as a placeholder instead of appearing when submitting the PR
the list has now checkboxes when adding a ''x'' on the items
=> suggestion to PR template

client/src/components/Header.js, client/src/templates/layouts/Main.js
closes #710
Fix header nav to top
=> Fix header nav to top of page

client/src/components/StepWizard/StyledDiv.js, client/src/components/StepWizard/index.js, client/src/pages/NeedHelp.js, client/src/pages/OfferHelp.js
Adddind the link for terms and conditions above the email input box for both getHelp and needHelp options/steps
#753
=> adding terms conditions link to NeedHelp.js & OfferHelp.js

client/src/pages/Login.js
Fix Facebook login/signup icon as per issue https://github.com/FightPandemics/FightPandemics/issues/496
There are merge conflicts, ***HOWEVER*** I believe that the process that runs when you commit (I believe it is cleaning up the code) made a substantial amount of changes. None of them appear to break anything below, I just wanted to note that I only edited line 82 of this file. Please reject the PR if this is abnormal. I have confirmed that the master I was working from is still up to date.
1. I have checked that no one else is working on similar changes. Yes there are none I can see
2. I have read the latest [**README**] I have read it
(https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and …
=> Adjusted x padding of the SocialButton to 1.8 from 2.5 rem (y padding left at 2.5rem)

client/src/components/StepWizard/StyledDiv.js, client/src/pages/NeedHelp.js, client/src/pages/OfferHelp.js
Updating copy from onboarding pages / adding link to Privacy policy
#763
=> updated copy texts/links from step 3 on onboarding pages

client/src/pages/AboutUs.js
Updated the contact us email address in About us page
=> Update contact email

backend/config.js, backend/lib/endpoints/users.js, backend/lib/plugins/auth.js
Fix bug with mongo id in JWT token from Auth0 (was also problem in the Auth0 rules script that's fixed now)
use correct url concatenation for mongo id key in jwt token 
and handle potential errors appropriately
=> fix bug with mongo id in jwt token

client/src/pages/CreateOrganizationProfile.js
Resolves #780 
Must have been a merge resolution mistake. Vik - this will solve I think the problem you reported yesterday: 
" the "Create Profile" button on the Create Organization page  isn't working in staging. Any ideas why?"
=> remove duplicate create-org-profile needs

backend/lib/plugins/auth.js
Resolves #773 
Just an variable name issue.
=> check Auth0 token.payload.exp to refresh token

backend/lib/endpoints/schema/users.js, client/src/pages/EditProfile.js
fix #795 by updating the LinkedIn URL validation rules, also allowing dashes
=> Fix LinkedIn URL validation

client/src/assets/data/createOrganizationProfile.js, client/src/pages/CreateOrganizationProfile.js
Changes the organization profile form
closes https://github.com/FightPandemics/FightPandemics/issues/801
=> Org profile ui func

client/src/pages/EditProfile.js
until avatar upload is implemented (issue 715)
Resolves #797 - to reduce confusion around ability to change avatar.
Implementing feature is issue #715  
=> temporarily hide EditProfile ChangePicButton

client/src/components/CreatePost/Form/Form.js
Addresses issue:
Closes #818 
Fixes Select dropdown onChange handlers to properly submit selected values.
Removes unused onChange props.
=> Fix Create Post Form - expires and shareWith Dropdowns

backend/scripts/import-posts/init-sourced-by-fp-users.js
Resolves #830 
Thanks @cvaldez98 for helping me find this  - this should address the issue we found specifically with these FP-specific organizations:
```
TypeError: Cannot destructure property 'address' of 'location' as it is undefined.
```
You will need to re-run `docker-compose exec backend-service npm run import-posts` for success.
=> add generic location to sourced-by-fp users

backend/lib/models/IndividualUser.js, client/src/assets/data/filterOptions.js
Resolves #846 
I think ideally we'd have a common types/constants among F/E & B/E but I guess this would have to be an NPM package. Any thoughts on this @robinv85 
I changed IndividualUser type to "Individual"  (uppercase) for consistency with OrganizationUser. I will update staging DB once this is merged. Interestingly, post creation would have error if we were using Author.js but we're not for anything. @joaofnds do you recall why we couldn't use the subschemas?
=> use Individual consistently as type

client/src/components/Profile/Activity.js
This issue closes #845 , providing a temporary fix to get the Profile page working again on the master branch.
I'll need to look into this further as a lot of the buttons for posts under My Activity probably aren't working. For now, this should fix the page at least.
=> Fix for blank profile page on master branch

backend/lib/endpoints/auth.js, backend/lib/endpoints/users.js, backend/lib/models/IndividualUser.js, client/src/components/CreatePost/CreatePost.js, client/src/pages/Feed.js
=> Displaying the Organizations list in the create post modal

client/src/templates/RouteWithSubRoutes.js
fixing bug introduced when last PR I merged!
=> fixing error I introduced when last PR was merged

client/src/pages/CreateOrganizationProfile.js
Resolving the following small bug:
=> fix small bug on create organization page

client/src/components/Header.js
Added menu icon from Zeplin design.
=> added menuicon from zeplin design

client/src/components/Header.js, client/src/pages/Home.js, cypresse2e/cypress/integration/e2eTests/home/homePage.spec.js
Changed the text of the main page from 'A place to give and get help' to '     A place to offer and receive help
#879 
'
=> Replaced the heading message with the correct one

client/src/components/Header.js, client/src/templates/layouts/NavigationLayout.js
Fixes and closes issue #865 .
If no organizations are present, the Organization menu item is removed.
=> Fixes mobile Organization list and desktop list styling

client/src/pages/EditAccount.js, client/src/pages/EditProfile.js
This PR resolves #861 adding redirection on save to the main profile
=> added redirection to the main profile on save from edit account/profile

client/src/pages/NeedHelp.js, client/src/pages/OfferHelp.js
Reducing transition time by half from `Home` to `NeedHelp` and `OfferHelp`.
#779
=> Reducing transition time from Home to NeedHelp and OfferHelp

client/src/pages/Profile.js
For this time, we will set up the api call on the user profile to get all posts for now. We can revisit to add pagination afterward.
This PR resolves #897
=> setting the number of posts for userprofile display to -1

client/src/components/Footnote.js
Just adding the blog link to the footer.
Resolves #902
=> add blog link to footer

client/src/templates/layouts/Main.js, client/src/templates/layouts/MobileTabs.js
Fix Header and MobileTabs interaction so spacing is consistent across all pages whether the page has just a Header or Header and MobileTabs both.
=> Fix Header and MobileTabs positioning

backend/lib/endpoints/schema/sendgrid.js, backend/lib/endpoints/sendgrid.js, client/src/pages/NeedHelp.js, client/src/pages/OfferHelp.js
This PR integrates sendgrid on the frontend :). 
Resolves #731
=> Integrate sendgrid on the frontend

client/src/pages/OrganizationProfile.js
Resolves #943 
Dunno why I didn't have an error locally BUT this should prevent the undefined error in all envs (similar to code in individual `Profile.js` page)
=> add org.location default for undef err

client/src/components/Feed/PostCard.js, client/src/components/Feed/StyledComment.js
=> Fixed word-wrap bug

client/src/components/Feed/Post.js
=> Every post, regardless of length, has a line

client/src/components/Feed/PostCard.js, client/src/components/Feed/PostSocial.js
=> updated likes to be displayed as like or likes and added space

client/src/components/Feed/NestedComments.js, client/src/components/Feed/Post.js, client/src/components/Feed/StyledCommentButton.js
=> On-hover, post page buttons match styleguide colors

client/src/pages/EditOrganizationAccount.js, client/src/pages/OrganizationProfile.js
I removed "I need help/I want help" in the organization profile page for #869.
For #878, the organization account information bug is fixed. I added undefined check for it. Right now the checkboxes can display the needs part correctly.
=> Resolve the issues #869 and #878

client/src/components/Feed/Post.js
Closes #877 
Added a line to display the city name of Posts in the Feed when available.
I added a line to check and display the city of a
=> Add city name when available

client/src/components/Header.js, client/src/pages/Home.js
This PR just updates the home page text form receive to request
resolves #995
=> updating home page text from recieve to request

client/src/components/Header.js
To fix this warning:
```
Warning: Each child in a list should have a unique "key" prop.
Check the top-level render call using <Menu>. See https://fb.me/react-warning-keys for more information.
in MenuItem (at Header.js:115)
in Unknown (at NavigationLayout.js:281)
in div (created by Drawer)
in div (created by Drawer)
in Drawer (created by Drawer)
in Drawer (at NavigationLayout.js:268)
in div (at NavigationLayout.js:267)
```
=> add key to menu org item

client/src/components/Feed/NestedComments.js, client/src/components/Feed/Post.js, client/src/components/Feed/utils.js
* Refactor authorProfileLink to Feed/utils
* Links comment author name and avatar to profile
closes #944
=> Link comment avatar and name to profile

client/src/utils/userInfo.js
I small bug was introduced when I refactored the `getInitials` utility, this should handle more edge cases :) 
resolves #1012
=> fix bug in getInitialsFromFullName Function

client/src/components/Button/BaseButton.js, client/src/components/Button/SubmitButton.js, client/src/components/CompletedProfile/CompletedProfile.js, client/src/pages/Login.js
Reverting changes made on #813
This PR reverts #813
=> reverting changes that were made on PR #813

client/src/components/Input/LocationInput.js, client/src/components/StepWizard/WizardNav.js, client/src/constants/gtm-tags.js, client/src/pages/NeedHelp.js
Add gtm tags to Needhelp flow
closes #990
=> Add gtm tags to NeedHelp flow

client/src/components/Header.js, client/src/constants/gtm-tags.js, client/src/pages/Home.js, client/src/templates/layouts/NavigationLayout.js
Adds id tags to homepage and navbar
closes #988
=> Add ID tags for Homepage and Navbar

client/src/pages/Feed.js
Resolves #1027 
I'm going to look into the best way that "user" object always has the same shape when returned from B/E. For now this will fix the issue.
=> use safe operator in isAuthorOrg

backend/scripts/import-posts/init-sourced-by-fp-users.js
DRAFT for now to test in review env.
Will resolve #967
=> change sourced-by-fp email to admin@

client/src/pages/EditOrganizationProfile.js
=> remove Personal from org prof edit website label

client/src/components/Feed/Post.js, client/src/components/Feed/PostSocial.js, client/src/components/Input/AutoSize.js, client/src/components/StepWizard/WizardFormNav.js, client/src/constants/gtm-tags.js
Add GTM tags to Post 
closes #1031
=> Add GTM tags to Post

client/src/pages/EditOrganizationAccount.js, client/src/pages/EditOrganizationProfile.js
Bug fix for linkedin logo not displaying in organization profile:
fixes #1039
=> Linkedin icon in organization profile - bug fix

client/src/pages/Login.js
Fix overlapping text when open keyboard. IT should take care of #1032
=> fix overlap in forgot pass page

client/src/pages/CreateOrganizationProfile.js, client/src/pages/CreateUserProfile.js
added The UnderLine links to the create Profile Page, 1020 
Resolves #1020
=> added The UnderLine links to the create Profile Page, 1020 

backend/lib/models/Author.js, backend/lib/models/OrganizationUser.js, backend/scripts/import-posts/map-airtable-data.js, client/src/assets/data/createOrganizationProfile.js, client/src/assets/data/filterOptions.js
Resolves #1044 
Removing R&D as organization type as discussed with
To avoid confusion with R&D post type - which we still have:
We also have "Research" as industry if we want to track/use that for other purposes:
=> remove r&d organization type

client/src/components/Feed/Post.js
Add tag to Post view more, and small fixes
Just noticed that my PR #1046 had left off a commit. Didn't noticed that my push failed
=> Add tag to Post view more

client/src/components/Header.js, client/src/pages/Faq.js, client/src/pages/Feed.js, client/src/pages/Home.js, client/src/pages/Login.js, client/src/pages/PrivacyPolicy.js, client/src/pages/TermsConditions.js, client/src/templates/layouts/NavigationLayout.js
https://github.com/FightPandemics/FightPandemics/issues/973
=> update copy - issue #973

client/src/components/Input/AutoSize.js
fix issue #1054 (send button is off when using tablets and on some mobile screens.)
=> Fix send button on tablets

client/nginx.conf
Adds compression for additional files. Resolves #1076 
@doheekim93 - this decreased "Time to Interactive" by over 50%. Very easy win. Plus the 5s is on emulated "Good 3G" so now it should be pretty good to excellent for most scenarios. We can further improve later.
@mannykary not sure if there is (much) of a benefit to pre-compressing via webpack vs having nginx do compression but we can do that later if needed I think. If we want to, we need to "eject" from create-react-app so a bit of headache to do now.
=> compress additional mime types

client/src/pages/Profile.js
Adds edit/delete functionality for posts in `My Profile` page:
resolves #1061
=> Add Delete/Edit ellipses for profile posts

client/src/components/Feed/PostSocial.js, client/src/components/Input/LocationInput.js, client/src/components/StepWizard/AnswerButton.js, client/src/pages/NeedHelp.js
Fix various GTM tag bugs
closes #1081
=> Fix various GTM tag bugs

client/src/pages/Feed.js
Onboarding user will land on the correct feed page for `Requesting help` or Offering Help` 
fixes #1019
=> Landing onboarding user to correct feed page

client/src/components/Button/SubMenuButton.js, client/src/components/CreatePost/CreatePost.js, client/src/components/Feed/Post.js, client/src/components/Feed/PostSocial.js, client/src/components/StepWizard/WizardFormNav.js
Previous implementation used `document.referrer` but it was only working sometimes. @rabbi08  reported it wasn't working on staging.
This one uses the Window.history object. 
Closes #1018
=> When 'back' button is clicked, redirect user to previously visited page

client/src/pages/Feed.js
Removing `providers` filter when onboarding user lands on Feed 
resolves #1094
=> Removing provider filter from Feed page when onboarding

client/src/components/Feed/PostSocial.js, client/src/components/Input/Checkbox.js, client/src/components/StepWizard/WizardCheckboxItem.js, client/src/pages/OfferHelp.js
Fix various GTM bugs persisting after PR #1091
closes #1081
=> Fix various GTM bugs

client/src/components/Input/Checkbox.js, client/src/components/StepWizard/WizardCheckboxItem.js
There was a bug introduced in 1091, so @jyclam I will rever those two files, and that should help with solving this bug. 
Thanks @nadinejuraschek for pointing it out!!!
=> Fix bug for check boxes not being clickable introduced by #1091

client/src/components/StepWizard/WizardCheckboxItem.js
Adds pointerEvents: none to wizardNav specifc checkboxes 
closes #1081
related to #1100
=> Add pointerEvents: none to WizardCheckbox

client/src/templates/layouts/MobileTabs.js
=> Updated the mobile version from Feed to Help Board

client/src/components/Feed/PostSocial.js
Fixes GTM tags for Share post button(s) in /Post/:postID and /feed
closes #1081 completely
=> Fix GTM tags for Share post button

client/src/components/Feed/Post.js
=> fixed back button visibility when user clicked on comment icon

client/src/components/Feed/FeedWrapper.js, client/src/components/Profile/ProfileComponents.js, client/src/pages/Feed.js, client/src/pages/Profile.js
closes #1107
- increased the size of the button on mobile (2.2rem to 4rem) so it is big enough to tap with a finger
=> mobile button size to add post in feed doubled

client/src/components/Feed/PostSocial.js
Fixes render bug impacting performance
closes #1141
=> Move styled calls outside of PostSocial component

client/src/pages/Feed.js
This issue happened when I renamed `need or give help` to `offer or request help`. This should be fix for now
This PR resolves #1137
=> fixing filters for offer/request help on mobile (changed Feed.js)

client/src/pages/OrgProfileComplete.js
Change wording on button from Check the Feed to Check the Help Board
#1161
=> Change wording in button after org profile creation

client/src/components/CreatePost/StyledPostAs.js, client/src/components/Feed/FilterAccordion.js, client/src/components/Feed/Post.js, client/src/components/Feed/StyledAccordion.js, client/src/components/StepWizard/WizardCheckboxItem.js, client/src/constants/gtm-tags.js
Fixes feed GTM tags
closes #1147
=> Fix feed GTM tags

client/src/constants/urls.js, client/src/pages/EditOrganisationProfile.js, client/src/pages/EditProfile.js, client/src/pages/OrganisationProfile.js, client/src/pages/Profile.js
Changes OrgProfile social media link validation 
closes #1140
=> Change Org social media links validation

client/src/components/Feed/Post.js, client/src/pages/Feed.js
2 PRs that are critical back to master
=> Merge rc/v1.1 -> master

backend/lib/endpoints/organisations.js
hotfix for prod, looks like the message for a duplicate is still not there, giving this a try!
=> Fix duplicate mongo error, adding if name === MongoError to the check

client/src/components/Button/FeedbackButton.js
=> fix issue #677

README.md
Add Production build status badge
=> Add Production build status badge

backend/lib/endpoints/posts.js
Resolves #1199 
Draft until I got confirmation from at least one PM but I'm pretty this is fine - we're not using the data for anything now. See: https://fightpandemics.slack.com/archives/C0113DAESF3/p1594990360130300?thread_ts=1594664667.101900&cid=C0113DAESF3
=> remove comment.author.location

client/src/App.js, client/src/actions/authActions.js, client/src/index.js, client/src/pages/Login.js, client/src/templates/layouts/NavigationLayout.js
Moving adding the datalayer  to Login page from Navbar
fixes #1190 
=> Add datalayer to GTM in login 

client/src/components/CreatePost/CreatePost.js, client/src/components/CreatePost/StyledPostAs.js
=> add scroll to auto in create post

client/src/components/Feed/Post.js
Added own-user check to prevent non eligible users to edit/delete
fixes #1188
=> Fix non own-users to edit delete

client/src/templates/layouts/NavigationLayout.js
Feedback thanksModal closes after 3 seconds 
closes #1157
=> Add auto close timer on Feedback thanksModal

client/src/components/Feed/Post.js, client/src/components/Feed/PostSocial.js, client/src/templates/RouteWithSubRoutes.js
=> redirect unsigned user appropriate post after viewmore clicked

client/src/components/Header.js, client/src/constants/gtm-tags.js, client/src/templates/layouts/NavigationLayout.js
=> Added feedback GTM tags on Mobile web (scrappy but surely)

client/src/components/Feed/PostSocial.js
=> hiding social icon labels on mobile view

client/src/components/CreatePost/Form/EditForm.js, client/src/components/Feed/Post.js, client/src/pages/Feed.js, client/src/pages/OrganisationProfile.js, client/src/pages/PostPage.js
=> Refactor Ellipsis conditional in feed and post

client/src/components/Feed/PostCard.js
Fixes Post title alignment and PostCard background width
closes #999
=> Fix Post title alignment and background

client/src/components/CreatePost/CreatePost.js, client/src/pages/Feed.js, client/src/pages/OrganisationProfile.js, client/src/pages/Profile.js
=> Create post succeed modal refetch posts even onCancel

client/src/components/Typography/TextLabel.js, client/src/pages/Home.js
Resolves #1242 
before v after 
_I also added a little transition on the left content block so its a little smoother when transitioning back and forth between mobile and desktop_
🚨This also helps the homepage for issue #1244
=> Remore additional homepage text

client/src/components/Feed/Posts.js
=> added horizontal rule between posts

client/src/components/StepWizard/WizardFormNav.js
=> one more level deep to see if the state is defined

client/src/components/Header.js, client/src/pages/OrgProfileComplete.js, client/src/pages/PostPage.js
Displays user friendly message if post is deleted, when the user opens up a shared link related to a post that has been deleted:
fixes: #1155
=> Display user friendly message if post is deleted

client/src/templates/layouts/NavigationLayout.js
Resolves #1262 
Let's merge into `master` then I'll update `rc/v1.1`. 
This one is pretty simple so we don't need a 2nd dev reviewing. @nivetheatha  - confirm it is okay after the review branch build and then if all is good @idjevm please complete merge.
=> check user _id or id in mobile profile link

client/src/pages/CreateOrganisationProfile.js, client/src/pages/CreateUserProfile.js, client/src/pages/EditAccount.js, client/src/pages/EditOrganisationAccount.js
=> adding error to useform incase entering wrong address
