FightPandemics/FightPandemics

- client/src/assets/data/filterOptions.js
- client/src/components/Accordion/FilterAccordion.js
- client/src/components/Button/CustomButton.js
- client/src/components/FilterBox/FilterBox.js
- client/src/components/Input/LocationSearch.js
- client/src/components/List/CustomList.js
- client/src/components/Tag/FilterTag.js
- client/src/components/Typography/Title/FilterTitle.js
- Added location search bar
- Added two Quit/Apply buttons at the bottom
- Clicking "Apply filters" saves selected filters
- Clicking "Quit filters" removes all selected filters
- An associated accordion panel gets active and opened when a user clicks on a filter
- Filter tags have selected styling even after closing and reopening the modal
WIP:
- Dynamically render accordions and location results
- Replace the icon on the accordions
- Replace the icon next to "Share my location"
- Change font style of the location search input text
> Frontend Feed - Add state management 

- docker-compose.yml
Probably fixes #85 and  React hot reloading not working inside docker
might need to investigate if there is more config not working correctly in the docker-compose file (due to use of double quotes)
> remove some quotes that seem to break docker-compose config

- client/src/pages/CovidScreening/CareFacility.js
- client/src/pages/CovidScreening/PlannedCareFacility.js
- client/src/pages/CovidScreening/Under18.js
- client/src/pages/SymptomsCheck.js
- when under 18, the process is terminated and directed to a particular screen.
- when symptomatic it gives guidance in line with [this](https://github.com/andreslarezbas/covid19healthbot/blob/master/screening_protocols/covid_19_screening_protocol_cdc_apple.pdf).
NB: - a couple of sections and scenarios are still missing
> initial Version

- backend/lib/components/Auth0.js
- backend/lib/endpoints/auth.js
just some small tweaks to the auth code
have double checked everything and updated the settings on Auth0, it's working now and we just need to update the react app to call the right API call (for email/password signup and login).
few small things i would like to change but for now seems to work ok. 
Maybe we could have separate routes for /signup and /login with username / password, so it doesn't  call the `createUser` on every attempt to call `/api/auth/authenticate`. 
Also, sending the error info from Auth0 to the client seems like a bad idea, so would like to improve the error handling a bit.
> some tweaks to update auth flow, fixed email / password signup & login

- README.md
I have added quite a bit to the `theme.js` and it would be good if devs knew about the theme so it can start being used. However, we don't have a ThemeProvider handling the theme and are just importing the theme file at the moment, so I'm not sure if it's worth having this info here now or add it later when ThemeProvider is in use. @anniegiang,  @MohamedEl1, @neemiasjnr  would you mind reviewing this please. :pray:
> Add theme info to Frontend guidelines in README 

- docker-compose.yml
Noticed a missing `/` at the end of the client `node_modules` mount. The trailing slash is critical for it to be excluded from the container mount, and also not have it modified by any `npm install` run on the host: https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder#comment71220422_37898591
> Add missing / to node_modules mount

- backend/Dockerfile.dev
- client/Dockerfile.dev
- geo-service/Dockerfile
This cut down the image sizes by more than half. Should speed up builds.
> Use alpine/slim base images

- client/src/components/Footnote.js
As pictured below, the footnote seems to be in a fixed position when scrolling a page. This PR attempts to fix this so that the footnote stays at the bottom, and should only be seen once reaching the bottom of the page.
> Keep footnote at the bottom of the page

- .github/workflows/review-delete-workflow.yml
Fix the review-delete workflow. I believe that the `master` branch in `branches-ignore` is preventing this workflow from being run
> Remove ignore branch master from review delete workflow

- backend/lib/endpoints/feedback.js
- backend/lib/endpoints/schema/feedback.js
- backend/lib/index.js
- backend/lib/models/schemas/Feedback.js
Closes [148](https://github.com/FightPandemics/FightPandemics/issues/148)
- Adds feedback data model to mongo
- Adds fluent-schema for feedback data coming from the body of request
- Adds `api/feedback` endpoint to be used for form submission
- Before saving it ensures that the each user and ip can only submit one feedback form. This was 
discussed with @robinv85 as a desired check.
> Create endpoint/backend for feedback form

- client/package-lock.json
- client/package.json
- client/src/pages/OfferHelp.js
Fixes issue #178 where the path from after submitting your email in offer help does not take you to the Feeds page like it should.
* Changes the OfferHelp.js file.
* The path in line 194 was originally set to /medical but I changed it to /Feed so that the next page will be Feed.js.
> Fixed path from Offerhelp issue #178

- .github/workflows/review-build-url.yml
Automatically post the review build URL to a PR when it is opened. Only runs on branches with the `feature/` prefix, since those are the only branches that are built and deployed to AWS review environment.
* Added a new Github workflow to post a comment on the PR with the build URL when it is opened
> Add post review build URL to PR workflow

- backend/config.js
- main.tf
This allows the backend container to connect to our MongoDB Atlas cluster using the SSM parameters stored in AWS. These parameters were generated when configuring the cluster with the Terraform code in the infrastructure repo.
* Get the AWS SSM parameters for the MongoDB host, user, and password, and build the `MONGO_URI` environment variable.
> Terraform: use full MONGO_URI

- .github/pull_request_template.md
when clicking on the pull requests link on the PR description when using a template
example
would go to a link that filters the PR's opened by the user example 
https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3Astavares843+archived%3Afalse+sort%3Aupdated-desc
instead of a link with the link of all the PR's example
https://github.com/FightPandemics/FightPandemics/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
> fix link on PR template

- backend/lib/endpoints/schema/users.js
Ran into this error after rebasing on master:
{"level":50,"time":1589290896025,"pid":40,"hostname":"129f21ed4e30","name":"FastifyError [FST_ERR_SCH_BUILD]","code":"FST_ERR_SCH_BUILD","message":"FST_ERR_SCH_BUILD: Failed building the schema for POST: /api/users, due error schema is invalid: data.required should NOT have duplicate items (items ## 2 and 1 are identical)","statusCode":500,"msg":"FST_ERR_SCH_BUILD: Failed building the schema for POST: /api/users, due error schema is invalid: data.required should NOT have duplicate items (items ## 2 and 1 are identical)","stack":"FastifyError [FST_ERR_SCH_BUILD]: FST_ERR_SCH_BUILD: Failed building the schema for POST: /api/users, due error schema is …
> remove duplicate user.country fluent-schema prop

- client/src/components/Button/FeedbackButton.js
Removes the 1px border that was shown in the original issue ticket.
* The issue stems from inbuilt styles in the antd-mobile (Ant Designs) Button Component. In particular the following media query exists and I suppose need to be manually overridden in the component using the antd-mobile (Ant Designs) Button Component.
```
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 2dppx) {
...
html:not([data-scale]) .am-button-ghost::before {
...
border: 1PX solid #108ee9;
...
}
```
* The following was added to the client/src/components/Button/FeedbackButton.js file to suppress the border shown above:
```
&.am-button-ghost:before {
border: none !important;
}
```
* Is there a better way?
> Fixed blue border #289

- backend/lib/endpoints/geo.js
- backend/lib/index.js
- client/Dockerfile
- client/nginx.conf
- client/src/pages/Medical.js
This hooks up the client container to the backend container in Fargate. I had to add an `nginx.conf` in the client container, and proxy requests to `/api` to the backend container.
I also exposed the Fastify Swagger docs at `/api/documentation`.
* Add `nginx.conf` file
* Set Swagger doc route to `/api/documentation`
* Geolocation endpoint fixes - change to get, add default location if not set, remove authentication in the backend
Closes #337, #338, and #278
> Connect client to backend through NGINX; expose Swagger API docs

- client/src/components/Feed/StyledComment.js
Avatar icon is squished below its size of 32x32 by sibling textarea node and as a result, a bit of the image is cut off. I've added a CSS rule to calculate the textarea width based on the avatar horizontal size + offset.
Also removed unused css.
* A few notes on your commits.
* To help understand them.
**Issue:**
**Fixed:**
iPhone X:
There's an issue with the current way of nesting comments and replies. At a certain point, the comments are offset so far to the right that there's no horizontal space left. **I've confirmed that this is a pre-existing issue prior to my changes.**
Problem on PR branch:
Problem on Master branch:
I will submit a bug for this issue.
> #279 fix icon layout

- backend/lib/plugins/mongoose-connector.js
Add syncing between the indexes defined at model and the ones present at the database.
This way, it will ensure that index created at the database and defined at model schema are always in sync.
If a new index is added at the schema it will create at the database.
If an index is removed from the model, it will remove it from the database too.
Closes #375 
* Add calls to `syncIndexes()` for each model at `mongoose-connector`
http://thecodebarbarian.com/whats-new-in-mongoose-5-2-syncindexes
> Add automatic index syncing between model and db

- backend/lib/endpoints/posts.js
Fix case for setting Post expiration date with `forever` option
Closes #390 
Expected Behaviour:
`posts.expireAt` is unset/null for `"forever"` option.
> Fix case of setting post expiration with 'forever' option

- client/src/pages/SymptomsCheck.js
When clicking on options, its either you select all options or you select none of these. It was missing the '!none' next the checked under AnswerCheckbox.
> Fixed unselect/select options

- .github/workflows/review-delete-workflow.yml
- .github/workflows/review-workflow.yml
- .github/workflows/staging-workflow.yml
- main.tf
This enables fetching of Auth0 secrets based on the environment being deployed. I have set up three new tenants in Auth0: staging, review, and production.
Instead of storing the Auth0 secrets in the GitHub repo secrets, I have moved them to AWS SSM Parameter store, which is more secure, and easier to separate by environment (each environment has its own AWS account)
Resolves #350 
3. The name of this branch is: **`feature/<branch_name>`**.
5. …
> Separate Auth0 tenants for each environment

- backend/lib/models/Post.js
Resolves #413 
As per discussion: https://github.com/FightPandemics/FightPandemics/pull/408#discussion_r427715558
The fluent schema (url/email) would prevent a value with leading/trailing whitespace but for consistency & non-API data loading I've added `trim: true` to the schema.
> trim Posts.externalLinks items

- client/package-lock.json
- client/package.json
fix https://github.com/moment/moment/issues/5484# by upgrade to moment ^2.25.3 (installs 2.26.0).
Resolves #450
> upgrade moment to ^2.25.3

- backend/lib/endpoints/posts.js
- backend/lib/endpoints/schema/posts.js
- backend/lib/plugins/auth.js
Closes #411 
Add an additional decorator in the Fastify auth plugin, `authenticateOptional` that doesn't return a `401 Unauthorized` if there is no Authorization header with JWT in the request, but instead it optionally decodes the token to get user id, and otherwise just allows the request without doing anything.
This moves any possible authorization logic to the other handlers, for example I've updated the  `GET /api/posts` a bit to use this handler, but it will have to be further implemented to adjust the right query to mongo db to use this functionality ( cc @Naraujo13  @joaofnds )
> feat: add optional authentication decorator in fastify for API #411

- backend/lib/plugins/error-handler.js
Fix the call to Sentry by passing in `error` instead of `err`
> Bugfix: error handler - pass proper error object to Sentry

- backend/lib/plugins/error-handler.js
I was having an issue with docker a proxy request error while trying to send requests to the backend from the client. After talking with @mannykary he discovered that there was a bug in the new error plugin he installed. This fixes that bug.
> Fix bug in error handling

- backend/lib/endpoints/posts.js
Add pagination to `/posts` endpoints with standard page size of 5 records.
Closes #126 
This is a simple pagination method using `skip` and `limit`.
It was discussed at #197 about using other pagination methods to avoid possible duplicates when a record is added and changes the record order (e.g. a record added that would be on the first page because is near the user, pushes the fifth record to sixth, making it to be displayed again when fetching the second page). Since this shouldn't happen frequently and the effect is not that big for the user (just single repeated post), I'm submitting this simpler version for MVP and we can discuss and improve it later on.
> Add pagination to /posts endpoint

- backend/lib/plugins/error-handler.js
All errors, including 4xx errors for bad request or unauthorized, are being sent to Sentry. This will become very noisy in production. Instead, we should only send 500 errors to Sentry.
I refactored the check that was used in `defaultErrorHandler` to a new function `isInternalServerError`, so that it can be used in `errorNotifierHandler`.
> Send only 500 errors to Sentry

- .gitignore
- client/src/components/StepWizard/WizardCheckboxItem.js
- client/src/pages/OfferHelp.js
In the "Give Help" page, on section 1/3, the user was not able to toggle the checkboxes when clicking the option divs:
The user can now click on the option divs to toggle the checkboxes.
The Ant Design `Checkbox.CheckboxItem` component was preventing the div clicks from bubbling up and toggling the checkboxes. I removed `Checkbox.CheckboxItem` and now the `WizardCheckboxItem` component uses Ant Design's `Checkbox` component.  I used `AnswerCheckbox`'s implementation for guidance. 
Closes #529
3. The name …
> [529] In the "Give Help" page, clicking divs with text options toggles the checkboxes

- client/src/components/Feed/Post.js
Uses correct variables from `post.author` for post header in feed. Resolves #566 
**Has photo**:
**No photo**:
There is still the backend issue of these not being updated when the user updates their own or org logo but this will be dealt with separately but before MVP launch.
6. There are no console warnings and …
> use post.author vars in post header

- client/package.json
- client/src/utils/validators.js
Our email validation did not check whether the email's top-level domain was valid. 
As described in #537, any top-level domain of length >= 2 was valid. 
The user can submit the sign-up form if their email contains a valid top-level domain registered with [ICANN](https://www.icann.org/resources/pages/tlds-2012-02-25-en).
The `tlds` package contains an up-to-date list of valid top-level domains scraped from ICANN.
You can check out the full list of top-level domains [here](https://github.com/stephenmathieson/node-tlds/blob/master/index.js). 
Closes #537
> [537] Email validation fix - validate email top-level domains on sign-up

- backend/lib/models/Comment.js
I noticed this error when I ran the latest code in master:
```
backend-service    | /app/lib/models/Comment.js:68
backend-service    |   schema: CommentSchema,
backend-service    |           ^
backend-service    | 
backend-service    | ReferenceError: CommentSchema is not defined
backend-service    |     at Object.<anonymous> (/app/lib/models/Comment.js:68:11)
backend-service    |     at Module._compile (internal/modules/cjs/loader.js:1133:30)
backend-service    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
backend-service    |     at Module.load (internal/modules/cjs/loader.js:977:32)
backend-service    |     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
backend-service    |     at Module.require …
```
> Fix reference to commentSchema

- backend/lib/endpoints/auth.js
- backend/lib/endpoints/users.js
fixes #572 
throw & log errors if no mongo id found in JWT, to prevent creating users if the app or Auth0 is not correctly configured
> fix: throw & log errors if  mongo id is not found in JWT

- client/src/pages/OfferHelp.js
As of now, this just adds a redirect to /feed when a user wants to offer help chooses to skip providing an email
#604 
Note: We can merge this PR for now but leave the issue open so later we can integrate the filters as well.
> fix redirect for give help skip email opt

- client/src/components/StepWizard/WizardContainer.js
- client/src/components/StepWizard/WizardNav.js
This PR includes css changes to resolve the issue stated in #562. It aims to fix the position of the navigation buttons.
7. On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and …
> Added absolute position to the buttons and height to the container

- client/src/components/CreatePost/StyledPostAs.js
Fix fot the issue [581](https://github.com/FightPandemics/FightPandemics/issues/581) by setting the overflow-y to auto.
> Fix for issue 581 - Setting overflow-y to 'auto'

- backend/lib/endpoints/schema/posts.js
- backend/lib/models/Author.js
- backend/lib/models/Location.js
- backend/lib/models/Post.js
Define and export model enums on model definition files
> Define and export enum options instead of getting them from schema tree

- client/src/components/Button/FeedbackButton.js
Fix for [issue 564](https://github.com/FightPandemics/FightPandemics/issues/564)
Using !important to override specificity of the third party css border property in ant button. 
7. On the right hand side of this PR, I …
> Fix for issue 564 - No borders in mobile homepage

- backend/lib/endpoints/posts.js
Resolves #663 
This seems to address error:
```json
{
"level": 50,
"time": 1591740382050,
"pid": 29,
"hostname": "a612b4b6161a",
"reqId": 3,
"ok": 0,
"errmsg": "$substrBytes:  Invalid range, ending index is in the middle of a UTF-8 character.",
"code": 28657,
"codeName": "Location28657",
"name": "MongoError",
"msg": "Failed requesting posts",
"stack": "MongoError: $substrBytes:  Invalid range, ending index is in the middle of a UTF-8 character.\n    at MessageStream.messageHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:261:20)\n    at MessageStream.emit (events.js:315:20)\n    at MessageStream.EventEmitter.emit (domain.js:482:12)\n    at processIncomingData (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n    at …
```
> use substrCP instead of substr

- client/src/components/StepWizard/StyledWizard.js
- client/src/components/StepWizard/WizardNav.js
Fix for issue [#671 ](https://github.com/FightPandemics/FightPandemics/issues/671)
`  justify-content: space-between;
`
Forcing the divs to keep the same distance between each other throughout the steps.
`<Link to={"/"}>
<BackButton>
[...]`
Putting the button inside the link element, because in the Step1, the button was moving up a little bit.
4. This …
> Fixing button positioning in the wizard step navigation

- backend/lib/components/Auth0.js
- backend/lib/endpoints/auth.js
- backend/lib/endpoints/schema/auth.js
This `api/auth/change-password` endpoint makes a POST to Auth0's `/dbconnections/change_password`
https://auth0.com/docs/api/authentication#change-password to send a  change password email and ticket to the email provided. 
Test curl POST request:
```
curl -X POST \
http://localhost:3000/api/auth/change-password \
-H 'accept: application/json, text/plain, */*' \
-H 'cache-control: no-cache' \
-H 'content-type: application/json;charset=UTF-8' \
-H 'postman-token: {POSTMAN TOKEN}' \
-H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36' \
-d '{"email":"{YOUR EMAIL}"}'
```
Response:  
```
{
"email": "bleh@mail.com",
"responseMessage": "We've just sent you an email to reset your password.",
"token": ""
}
``` …
> [606] Password recovery endpoint: Sends user an email with a change password ticket to update password 

- .github/workflows/review-delete-workflow.yml
Review build delete workflows are broken because the terraform destroy command expects `aws_region` variable to be passed in, but none is passed in.
> Pass in required aws_region variable

- .github/workflows/production-workflow.yml
- .github/workflows/staging-workflow.yml
The client container needs the Google Tag Manager environment variable set for tracking/analytics. So we need to inject the variables from Github Secrets into the `.env` file when building the container.
This is required only for staging/production. The review environment does not need this set.
Fixes #699 .
> Add Google Tag Manager environment variable

- client/src/pages/AboutUs.js
- client/src/pages/Feed.js
- client/src/pages/NrMap.js
This PR finalizes the removal of all console warnings from the client, and closes PR #449 
Please guys let me know as I implemented what it seemed to work. I tested locally and it seems to work fine and nothing has been broken.
> refactored code to remove console warnings

- client/package-lock.json
- client/package.json
- client/src/components/StepWizard/StyledWizard.js
- client/src/pages/NeedHelp.js
- client/src/pages/OfferHelp.js
Add transition when transitioning from `Home` page to `Need Help` and `Give Help` to be more smooth using the `react-transition-group` library.
#689
> Add transition to NeedHelp and OfferHelp from Home

- client/src/components/Feed/Post.js
- client/src/components/StepWizard/WizardFormNav.js
- client/src/components/StepWizard/WizardNav.js
> Adding redirect back button from post to feed page

- backend/lib/endpoints/schema/users.js
- backend/lib/endpoints/users.js
- backend/lib/models/IndividualUser.js
- client/src/pages/CreateUserProfile.js
- client/src/pages/EditAccount.js
Resolves #806. Required for #805 . Enables option to hide address for public user profile.
Create user profile:
Edit user account information:
@robinv85 @Naraujo13 @joaofnds  for the data model I added a `hide` object as well will probably add for email as well soon-ish. This could be called `hides` or `privacy` not sure the best choice. Privacy settings and get quite complex so if we go down the path of something like LinkedIn/Facebook this will require migration later I'm sure. 
Also @robinv85 I removed the 'required' property as we'll have a default `false` due to earlier suggestion with respect to default+required being an anti-pattern. Not sure if there's a good reason to have both in mongoose SchemaType however (I don't think so...)
> add user hide address option

- client/src/actions/authActions.js
- client/src/constants/action-types.js
- client/src/hooks/reducers/feedReducers.js
- client/src/pages/Feed.js
- client/src/reducers/sessionReducer.js
- client/src/templates/RouteWithSubRoutes.js
Resolves #796 
This was an edge case after initial sign-up where the Auth0 user is authenticated but Mongo user not created yet. If user closes the tab or navigates with the browser bar to let's say /feed they still have log-in cookies but there is no user so we get an error.
In first commit I added at least some error message instead of "Something went wrong" to make other issues that may occur easier to troubleshoot:
2nd commit includes setting error state if an error is caught during `initAuth` and that error is checked in RouteWithSubRoute redirect logic - logging them out in such a case.
Open to alternate approaches.
> handle auth error edge case

- client/src/components/Feed/Post.js
- client/src/components/StepWizard/WizardFormNav.js
Centering the position of `Back` button in post page, and maintaining the visibility of the button when the post is collapsed : 
#804
> Fixing Back button position and visibility in Post page 

- client/src/pages/Profile.js
Fixes issue mentioned in and closes #824 
Most of the functionality was in place. The request to fetch posts was not being executed properly, and the posts were not being set correctly.
> Fix showing user's post activity on profile page

- client/src/components/CreatePost/CreatePost.js
- client/src/pages/Profile.js
Fixes bug introduced by #849 (I missed this in review and merged it to master)
Prop `user` for `CreatePost` was missing for the profile page.
Side note: 
I looked to see if we had designs laid out for the Profile page in Figma, and there wasn't anything to go off of. 
Does it make sense to be able to create a post from your profile page?
I was thinking it may be better to just refactor the button on the profile page to redirect you to the feed and open up the create post modal there. Thoughts?
> Fix/Proposal - Profile page create post functionality

- client/src/components/Header.js
We get this error after profile creation. I'm trying to figure out the best way for the B/E to always send the same data regardless of login/signup/create/etc but until then if we use the full safe operator like `user?.organizations?.` that is best. @MohamedEl1 do the same when adding the mobile.
Resolves #870 
```
TypeError: "o.organizations is undefined"
mc Header.js:110
React 6
unstable_runWithPriority scheduler.production.min.js:19
React 6
unlisten Router.js:33
r history.js:155
notifyListeners history.js:173
notifyListeners history.js:172
_ history.js:288
push history.js:369
confirmTransitionTo history.js:145
push history.js:350
e CreateUserProfile.js:217
s runtime.js:45
_invoke runtime.js:274
t runtime.js:97
Babel 2
> add safe navigation to user?.organizations?.

- main.tf
- terraform-task-module/alb-listener-rule.tf
- terraform-task-module/locals.tf
- terraform-task-module/logging.tf
- terraform-task-module/security-group.tf
- terraform-task-module/service.tf
- terraform-task-module/task-definition.tf
- terraform-task-module/variables.tf
This Terraform code was in a separate repo, but it makes deployments brittle since all branches point to the master branch of the other repo. So any change to that repo will reflect across all branches in this repo when it pulls in the module in `main.tf`.
Note that nothing has changed in the code. I just copied and pasted the module folder from the [tf-fargate-task](https://github.com/FightPandemics/tf-fargate-task) repo to this repo. I also had to update `main.tf` to point to the new module folder in this repo.
Resolves #883
> Add Terraform Fargate task module to main repo

- client/src/components/CreatePost/CreatePost.js
- client/src/components/Header.js
- client/src/pages/OrganizationProfile.js
Fixes and closes issue #867 
Partially addresses #865 key warning.
This fixes the blank screen error when trying to create a post from an organization profile page. Also fixes key errors in the console from lists in `Header` and `CreatePost`.
> Fix key errors and creating post from Organization page

- client/src/actions/authActions.js
- client/src/pages/EditOrganizationAccount.js
- client/src/pages/OrgProfileComplete.js
Resolves #864 
We are re-fetching user to update redux session store when an organization is added or updated (we don't have delete functionality yet).
@robinv85 you are right it does seem awkward mixing context & redux in `EditOrganizationAccount.js` but I see no other way without refactoring towards full use of redux.
Open to other ideas however.
> refetch user on org add/update

- main.tf
- terraform-task-module/alb-listener-rule.tf
- terraform-task-module/logging.tf
- terraform-task-module/task-definition.tf
- terraform-task-module/variables.tf
Adds a Datadog container to the Fargate task definition which will monitor the performance of both the client and backend containers. This container is only added in production; the staging and review environments do not require application performance monitoring.
In order to conditionally add the Datadog container to the task definition, I had to refactor the code in `task-definition.tf` to define each container as a Terraform map, rather than JSON. Then it was simply a matter of checking the value of `fp_context` and including the Datadog definition only if `fp_context` is `production`.
I also created a Slack channel called `#performance-monitoring`, where Datadog alerts will be sent to.
Resolves #762
> Add Datadog Fargate task monitoring

- backend/lib/endpoints/posts.js
Add the following fields to the response of the `GET /posts/:postId` endpoint:
- `liked`: boolean value with whether the user current logged user (if present) already liked this post or not
- `likesCount`: number of likes currently at this post
Both fields were already returned at `GET /posts/`, so this just adds the same structure to the single post response.
Closes #843
> Add liked and likes count at GET /posts/:postId

- client/src/components/StepWizard/WizardCheckboxItem.js
The checkbox styles in [Step 1/1 of offering help wizard](https://staging.fightpandemics.work/offer-help) have been changed to match the ones used in [create an organization profile](https://staging.fightpandemics.work/create-organization-profile) (clicking this link doesn't redirect properly to the create org profile page though) by using the styled antd checkbox instead of antd-mobile
Before:
After:
I also fixed the off-center text - it was because of a seemingly arbitrary height constraint, but if that was intended, let me know and I can revert it
Resolves #822
> Uniform checkbox styles and fix off-center text in offering help wizard

- backend/lib/endpoints/posts.js
- backend/lib/models/Comment.js
- backend/lib/utils.js
- client/src/assets/data/formToPostMappings.js
- client/src/components/Feed/NestedComments.js
Previously, the time ago comment timestamps only updated as you wrote a new comment. 
Now, the timestamps are only updated on page refresh.
Changes:
* moved timeAgo function to the backend and created a Comment post-save hook to set the timeElapsed property to a relative time string generated from the createdAt ISO Date object. 
* Moment relative time timestamps now only update on page refresh. 
Closes #938
Closes #959
> Fixed comments age reactivity issue

- client/src/components/CreatePost/CreatePost.js
- client/src/pages/Feed.js
User can hit 'Create a post' button repeatedly and create new posts. Currently, the success content is shown after first post and remains even after closing and reopening.
closes #876
> Clear Modal state on Modal close

- client/src/components/Feed/Post.js
- client/src/components/Feed/StyledPostPage.js
- client/src/pages/PostPage.js
Closes #928
Closes #952
You should no longer see div overflow in mobile AND post width should not expand based on content for both web and mobile web.
> Fixed word-wrap in mobile web

- client/src/components/Header.js
Fixes #1003 
I think we've made things confusing for F/E work by returning `_id` as `id` only sometimes from B/E. I think we should just always return it as `_id` - I created an issue here: #923
> check also user._id for profile link

- client/src/components/Feed/Post.js
- client/src/pages/EditAccount.js
- client/src/pages/EditOrganizationAccount.js
- client/src/pages/EditOrganizationProfile.js
- client/src/pages/EditProfile.js
- client/src/pages/OrganizationProfile.js
- client/src/pages/Profile.js
- client/src/templates/layouts/NavigationLayout.js
- client/src/utils/userInfo.js
This PR just fixes the initials in posts and org profile depending on name. If name only 1 word, then the avatar will be 1 letter, but if the name is 2 words or more, then the name will be 2 letters
This PR resolves #918 
Here is the outcome of this PR:
> Stetting orgs and posts avatar icon to only 1 initial or 2 initials

- backend/lib/endpoints/users.js
> Display orgList from individual Profile page

- client/src/components/Feed/PostSocial.js
- client/src/components/Profile/Activity.js
- client/src/pages/PostPage.js
I fixed the issue for #931 and now the user profile and organization's profile can show comment's icon as blue and comment count when the post has comments.
> Display profile and org profile comment's icon and comment count correctly

- client/src/components/StepWizard/WizardFormNav.js
- client/src/pages/ProfileCompleted.js
- client/src/templates/RouteWithSubRoutes.js
Changes:
* Some cleanup
* When the user clicks on `Back` on a post's page:
* The user is redirected to the previously visited page if they've visited another page within the fightpandemics domain. 
* The user is redirected to FEED if they've received a link to the post and were not redirected from another fightpandemics page. 
Closes #1018
> Post's Page: When 'back' button is clicked, redirect user to previously visited page

- client/src/pages/NeedHelp.js
- client/src/pages/OfferHelp.js
Redirects user to step 3 during onboarding when the user clicks on`show me posts from anywhere`, this PR also removes some console warnings from these 2 pages. 
resolves #1036
> Redirect the user to step 3 after clicking on "Show me posts from anywhere" on step 2 in both offer help and need help pages

- backend/lib/endpoints/posts.js
- backend/lib/models/Comment.js
- backend/lib/utils.js
- client/src/components/Feed/NestedComments.js
- client/src/components/Feed/StyledComment.js
- client/src/components/Feed/StyledPostPage.js
- client/src/hooks/reducers/postReducers.js
Changes:
* Added the property `edited` to the Comments aggregation on GET and set its value to false if  createdAt timestamp is **>=** the updatedAt timestamp. 
* Added a virtual property called `editTimeElapsed` that's a relative time stamp of the updatedAt timestamp. `editTimeElapsed` is only displayed in the frontend if the `edited` property is set to true. 
Closes #1001
> On comment PATCH, display an 'edited' tag and the relative update time timestamp in the comment

- backend/lib/endpoints/posts.js
- backend/lib/endpoints/schema/posts.js
- client/src/pages/OrganisationProfile.js
- client/src/pages/Profile.js
Resolves #904 
@vikjoshi On the org activity page the visibility=city(New York, user is not) can be seen and most recent one is 1st:
While on the feed it is hidden.
Let me know if this is what is expected.
> add GET posts/ param to ignoreUserLocation

- backend/scripts/import-posts/map-airtable-data.js
Resolves #1083 
This one we need to keep as `Organizations` because of Airtable source. I don't see a risk in someone accidentally renaming because the last PR was a one time thing but I put a comment just in case.
> name back to Organizations in airtable script

- backend/config.js
Resolves issue #842 
- In backend/config.js, adds `useFindAndModify: false` to mongo params
- Fixes mongo/mongoose useFindAndModify deprecation warning
> fixes mongo useFindAndModify deprecation error

- client/src/components/Footnote.js
> footer links now display more organized

- client/src/components/CreatePost/StyledPostAs.js
> Fix name overflow for org names

- terraform-task-module/alb-listener-rule.tf
We want to redirect any random subdomain like thisobviouslyisntarealsubdomain.fightpandemics.com and www.fightpandemics.com to fightpandemics.com. So I added a listener rule to the production load balancer to do a 301 redirect to https://fightpandemics.com.
Resolves #1151
> Redirect prod subdomains to fightpandemics.com

- backend/lib/endpoints/posts.js
Resolves #1143 
As per conversation initiated by Tony in Slack.
This hides the info we definitely don't want to leak - coordinates/address (as well as zip, neighborhood for now since we're not really using it for visibility/sharing yet). 
I wanted a re-usable function for both GET posts/:id & GET posts/ but since one is using aggregation pipeline and the other isn't I didn't see an easy way. Scopes like with sequelize would be nice...
> hide address/coordinates in post(s)

- .github/workflows/review-build-url.yml
- .github/workflows/review-workflow.yml
Match `rc/*` and `hotfix/*` branches for review workflow so that a review build can be spun up.
The build for `rc/v1.1` will be accessible at rcv11.fightpandemics.work.
> Match rc/* and hotfix/* branches for review workflow

- client/src/App.js
- client/src/templates/layouts/NavigationLayout.js
Adding the `userId` to `dataEntry` of google tag manager:
fixes #1088
> add userId in dataLayer of google tag manager

- client/src/actions/authActions.js
This might resolve the cookie issue we are getting with QA #1186  but I'm not 100% sure yet.
Basically we have two cookies for authentication:
1. `token` which contains the actual JWT containing user info. We can only clear this via http (so are dependent on the server). We need it this way  to prevent XSS attacks.
2. `remember` which only exists to enable offline logout. We don't want to be 100% dependent on the server to logout (e.g., if offline) so we have the 2nd non-httpOnly cookie.
If we try to get the user after clearing the `remember` token, the server will clear the `httpOnly` `token`. This might resolve our error we're experiencing with QA, but I'm not 100% sure yet.
But either way, at least for the majority of cases we are clearing both tokens on logout, unless the user is …
> clear httpOnly token on logout if online
